// <auto-generated />
using System;
using CatsMCP.Infrastructure.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CatsMCP.Infrastructure.Migrations
{
    [DbContext(typeof(CatDbContext))]
    [Migration("20250701040853_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CatsMCP.Domain.Entities.Cat", b =>
                {
                    b.Property<int>("CatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CatId"));

                    b.Property<string>("Alergias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AniosExistenciaRaza")
                        .HasColumnType("int");

                    b.Property<string>("ComidaPreferida")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Edad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmbeddingVector")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmparejamientosPotenciales")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnfermedadesCronicas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstadoAdopcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstatusConservacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Esterilizado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<string>("FechasVisitas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HistoriaPrevia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HistorialVacunacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JuguetesFavoritos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LugaresDescanso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NivelActividad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NivelSocializacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrigenRaza")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Popularidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Raza")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RazaPura")
                        .HasColumnType("bit");

                    b.Property<string>("Sexo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Temperamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TratamientosPasados")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CatId");

                    b.ToTable("Cats", (string)null);
                });

            modelBuilder.Entity("CatsMCP.Domain.Entities.CatEn", b =>
                {
                    b.Property<int>("CatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CatId"));

                    b.Property<string>("ActivityLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdoptionStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Age")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Allergies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Breed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BreedAgeYears")
                        .HasColumnType("int");

                    b.Property<string>("BreedOrigin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChronicDiseases")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConservationStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmbeddingVector")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FavoriteToys")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("IntakeDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Neutered")
                        .HasColumnType("bit");

                    b.Property<string>("PastTreatments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Popularity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PotentialMatches")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferredFood")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreviousHistory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PureBreed")
                        .HasColumnType("bit");

                    b.Property<string>("RestingPlaces")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SocializationLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Temperament")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VaccinationHistory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VisitDates")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CatId");

                    b.ToTable("Cats_EN", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
